[project]
name = "mlops_task1"
version = "0.1.0"
description = "Add a short description here"
authors = ["saifltr <bagmarusaifs@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
scikit-learn = "1.3.2"
scipy = "1.11.4"
matplotlib = "3.8.2"
optuna = "3.5.0"
wandb = "0.16.3"